package lang_types

import (
	"fmt"
	"strings"

	pgs "github.com/lyft/protoc-gen-star/v2"
)

type DartGenerator struct {
}

func GetDartGenerator() LanguageGenerator {
	return DartGenerator{}
}

func (d DartGenerator) MethodReturnType(method pgs.Method) string {
	return d.MethodType(method.Output(), method.ServerStreaming())
}

func (d DartGenerator) DocComment(method pgs.Method) string {
	commentLines := deleteEmpty(strings.Split(method.SourceCodeInfo().LeadingComments(), "\n"))
	commentLines = append(GetAnnotatedComment(method), commentLines...)
	if len(commentLines) == 0 {
		return ""
	}
	return fmt.Sprintf(" /// %s", strings.Join(commentLines, "\n///"))
}

func (d DartGenerator) AsyncModifier(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "async"
}

func (d DartGenerator) AwaitModifier(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "await"
}

func (d DartGenerator) MethodType(message pgs.Message, streaming bool) string {
	t := MessageType(message)
	if streaming {
		return fmt.Sprintf("$grpc.ResponseStream<%s>", t)
	} else {
		return fmt.Sprintf("Future<%s>", t)
	}
}

func (d DartGenerator) BuildMetadata(method pgs.Method) string {
	s := "(request: request)"
	if SdkAnonymous(method) {
		s = "()"
	}
	return "await buildMetadata" + s
}

func (d DartGenerator) MethodArguments(method pgs.Method) string {
	if SdkNoArguments(method) {
		return ""
	} else {
		return fmt.Sprintf("%s request", MethodParamType(method))
	}
}

func (d DartGenerator) DefaultRequestObject(method pgs.Method) string {
	if SdkNoArguments(method) {
		return fmt.Sprintf("var request = %s();", MethodParamType(method))
	}
	return ""
}

func (d DartGenerator) Annotations(method pgs.Method) string {
	isDep, msgDep := SdkDeprecated(method)
	isExp, msgExp := SdkExperimental(method)
	if isDep {
		return fmt.Sprintf("@Deprecated('%s')", msgDep)
	}
	if isExp {
		return fmt.Sprintf("@Deprecated('%s')", msgExp)
	}
	return ""
}

const DartServiceTpl = `// BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: {{ .TargetPath }}
{{ range .File.Services }}{{ range .Methods }}{{ if SdkTemplateGenerate . }}
    {{ DartAnnotations . }}
    {{ DartMethodReturnType . }} {{ .Name.LowerCamelCase }}({{ DartMethodArguments .}}) {{ DartAsync . }} {
        {{ DartDocComment . }}
        {{ DartDefaultRequestObject . }}
        return client.{{ .Name.LowerCamelCase }}(request, options: {{ DartBuildMetadata . }});
    }{{ end }}{{ end }}{{ end }}
// END Code generated by protoc-gen-trinsic. DO NOT EDIT.`

const DartDocTpl = `// BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: {{ .TargetPath }}
{{ range .File.Services }}
// {{ DocCreateServiceInjection . }}
// {{ DocMethodInjectionEnd }}
{{ range .Methods }}
// {{ DocMethodInjection . }}
// {{ DocMethodInjectionEnd }}
{{ end }}{{ end }}
// END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.`
