package lang_types

import (
	"fmt"
	"strings"

	pgs "github.com/lyft/protoc-gen-star"
)

func DartMethodReturnType(method pgs.Method) string {
	return DartMethodType(method.Output(), method.ServerStreaming())
}

func DartDocComment(method pgs.Method) string {
	commentLines := deleteEmpty(strings.Split(method.SourceCodeInfo().LeadingComments(), "\n"))
	commentLines = append(GetAnnotatedComment(method), commentLines...)
	if len(commentLines) == 0 {
		return ""
	}
	return fmt.Sprintf(" /// %s", strings.Join(commentLines, "\n///"))
}

func DartAsync(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "async"
}
func DartAwait(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "await"
}

func DartMethodType(message pgs.Message, streaming bool) string {
	t := MessageType(message)
	if streaming {
		return fmt.Sprintf("$grpc.ResponseStream<%s>", t)
	} else {
		return fmt.Sprintf("Future<%s>", t)
	}
}

func DartBuildMetadata(method pgs.Method) string {
	s := "(request: request)"
	if SdkAnonymous(method) {
		s = "()"
	}
	return "await buildMetadata" + s
}

func DartMethodArguments(method pgs.Method) string {
	if SdkNoArguments(method) {
		return ""
	} else {
		return fmt.Sprintf("%s request", MethodParamType(method))
	}
}

func DartDefaultRequestObject(method pgs.Method) string {
	if SdkNoArguments(method) {
		return fmt.Sprintf("var request = %s();", MethodParamType(method))
	}
	return ""
}
func DartAnnotations(method pgs.Method) string {
	isDep, msgDep := SdkDeprecated(method)
	isExp, msgExp := SdkExperimental(method)
	if isDep {
		return fmt.Sprintf("@Deprecated('%s')", msgDep)
	}
	if isExp {
		return fmt.Sprintf("@Deprecated('%s')", msgExp)
	}
	return ""
}

const DartServiceTpl = `// BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: {{ .TargetPath }}
{{ range .File.Services }}{{ range .Methods }}{{ if SdkTemplateGenerate . }}
    {{ DartAnnotations . }}
    {{ DartMethodReturnType . }} {{ .Name.LowerCamelCase }}({{ DartMethodArguments .}}) {{ DartAsync . }} {
        {{ DartDocComment . }}
        {{ DartDefaultRequestObject . }}
        return client.{{ .Name.LowerCamelCase }}(request, options: {{ DartBuildMetadata . }});
    }{{ end }}{{ end }}{{ end }}
// END Code generated by protoc-gen-trinsic. DO NOT EDIT.`
