package lang_types

import (
	"fmt"
	pgs "github.com/lyft/protoc-gen-star"
)

func DotnetBffMethodArguments(method pgs.Method) string {
	if SdkNoArguments(method) {
		return ""
	} else {
		return fmt.Sprintf("%s.Parser.ParseFrom(request.Data)", DotnetMethodParamType(method))
	}
}

const DotnetBFFServiceTpl = `// BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: {{ .TargetPath }}
{{ range .File.Services }}{{ range .Methods }}{{ if SdkTemplateGenerate . }}
            case nameof(service.{{ .Name.UpperCamelCase }}):
                response = await service.{{ .Name.UpperCamelCase }}Async({{ DotnetBffMethodArguments .}});
                break;
{{ end }}{{ end }}{{ end }}
// END Code generated by protoc-gen-trinsic. DO NOT EDIT.`
