package lang_types

import (
	"fmt"
	"strings"

	pgs "github.com/lyft/protoc-gen-star"
)

func GoMessageType(entity EntityWithParent) string {
	names := make([]string, 0)
	outer := entity
	ok := true
	for ok {
		name := outer.Name().String()
		names = append([]string{strings.Title(name)}, names...)
		outer, ok = outer.Parent().(pgs.Message)
	}
	return fmt.Sprintf("%s", strings.Join(names, "."))
}

func GoMethodReturnType(method pgs.Method) string {
	t := GoMessageType(method.Output())
	if method.ServerStreaming() {
		return fmt.Sprintf("AsyncIterator[%s]", t)
	}
	return t
}

func GoDocComment(entity pgs.Entity) string {
	return fmt.Sprintf("\"\"\"\n%s\n\"\"\"", entity.SourceCodeInfo().LeadingComments())
}

const GoServiceTpl = `# BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
# target: {{ .TargetPath }}
{{ range .File.Services }}{{ range .Methods }}
    async def {{ .Name.LowerSnakeCase }}(self, *, request: {{ MethodParamType . }}) -> {{ PythonMethodReturnType . }}:
        {{ PythonDocComment . }}
        return {{ DartAwait . }} self.client.{{ .Name.LowerSnakeCase }}(request)
    {{ end }}
{{ end }}
# END Code generated by protoc-gen-trinsic. DO NOT EDIT.`
