package lang_types

import (
	"fmt"
	"strings"

	pgs "github.com/lyft/protoc-gen-star"
)

func KotlinMessageType(entity EntityWithParent) string {
	names := make([]string, 0)
	outer := entity
	ok := true
	for ok {
		name := outer.Name().String()
		names = append([]string{strings.Title(name)}, names...)
		outer, ok = outer.Parent().(pgs.Message)
	}
	return fmt.Sprintf("%s", strings.Join(names, "."))
}

func KotlinMethodReturnType(method pgs.Method) string {
	return KotlinMethodType(method.Output(), method.ServerStreaming())
}

func KotlinDocComment(method pgs.Method) string {
	commentLines := deleteEmpty(strings.Split(method.SourceCodeInfo().LeadingComments(), "\n"))
	commentLines = append(GetAnnotatedComment(method), commentLines...)
	if len(commentLines) <= 1 {
		return fmt.Sprintf("/**%s */", strings.Join(commentLines, ""))
	}
	return fmt.Sprintf(" /** %s\n*/", strings.Join(commentLines, "\n* "))
}

func KotlinAsync(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "async"
}
func KotlinAwait(method pgs.Method) string {
	if method.ServerStreaming() {
		return ""
	}
	return "await"
}

func KotlinMethodType(message pgs.Message, streaming bool) string {
	t := KotlinMessageType(message)
	if streaming {
		return fmt.Sprintf("Flow<%s>", t)
	} else {
		return t
	}
}

func KotlinMethodArguments(method pgs.Method) string {
	if SdkNoArguments(method) {
		return ""
	} else {
		return fmt.Sprintf("request: %s", MethodParamType(method))
	}
}

func KotlinDefaultRequestObject(method pgs.Method) string {
	if SdkNoArguments(method) {
		return fmt.Sprintf("val request = %s.newBuilder().build();", MethodParamType(method))
	}
	return ""
}

const KotlinServiceTpl = `// BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: {{ .TargetPath }}
{{ range .File.Services }}{{ range .Methods }}{{ if SdkTemplateGenerate . }}
  @Throws(InvalidProtocolBufferException::class, DidException::class)
  suspend fun {{ .Name.LowerCamelCase }}({{ KotlinMethodArguments . }}): {{ KotlinMethodReturnType . }} {
	{{ KotlinDocComment . }}
    {{ KotlinDefaultRequestObject . }}
    return withMetadata(stub, request).{{ .Name.LowerCamelCase }}(request)
  }{{ end }}{{ end }}{{ end }}
// END Code generated by protoc-gen-trinsic. DO NOT EDIT.`
