package lang_types

import (
	"fmt"
	"strings"

	pgs "github.com/lyft/protoc-gen-star"
)

func RubyMessageType(entity EntityWithParent) string {
	names := make([]string, 0)
	outer := entity
	ok := true
	for ok {
		name := outer.Name().String()
		names = append([]string{strings.Title(name)}, names...)
		outer, ok = outer.Parent().(pgs.Message)
	}
	return fmt.Sprintf("%s", strings.Join(names, "."))
}

func RubyMethodReturnType(method pgs.Method) string {
	t := RubyMessageType(method.Output())
	return t
}

func RubyDocComment(method pgs.Method) string {
	commentLines := deleteEmpty(strings.Split(method.SourceCodeInfo().LeadingComments(), "\n"))
	if len(commentLines) == 0 {
		return ""
	}
	return fmt.Sprintf("# %s\n# @param [%s] request\n# @return [%s]", strings.Join(commentLines, "\n#"), MethodParamType(method), RubyMethodReturnType(method))
}

const RubyServiceTpl = `# BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
# target: {{ .TargetPath }}
nil
{{ range .File.Services }}{{ range .Methods }}{{ if SdkTemplateGenerate . }}
	{{ RubyDocComment . }}
    def {{ .Name.LowerSnakeCase }}(request)
        @client.{{ .Name.LowerSnakeCase }}(request, metadata: metadata(request))
    end{{ end }}{{ end }}
{{ end }}
# END Code generated by protoc-gen-trinsic. DO NOT EDIT.`
