name: 'Generate the SDK Wrappers'
description: 'Generate the SDK wrapper code for every language'
inputs:
  protoPath:
    description: 'Base path for proto files to compile'
    required: false
    default: '***SKIP***'
  renamePairs:
    description: 'Mapping pairs for folder names'
    required: false
    default: 'trust-registry=trustregistry,universal-wallet=wallet,verifiable-credentials=credential,templates=template,access-management=access_management,file-management=file_management'
  pythonPath:
    description: 'path for python output'
    required: false
    default: '***SKIP***'
  dotnetPath:
    description: 'path for .NET output'
    required: false
    default: '***SKIP***'
  dartPath:
    description: 'path for dart output'
    required: false
    default: '***SKIP***'
  golangPath:
    description: 'path for golang output'
    required: false
    default: '***SKIP***'
  typescriptPath:
    description: 'path for typescript output'
    required: false
    default: '***SKIP***'
  javaKotlinPath:
    description: 'path for Java / Kotlin output'
    required: false
    default: '***SKIP***'
  rubyPath:
    description: 'path for Ruby output'
    required: false
    default: '***SKIP***'
  swiftPath:
    description: 'path for swift output'
    required: false
    default: '***SKIP***'
  dashboardBffPath:
    description: 'path for .NET BFF output'
    required: false
    default: '***SKIP***'
  dashboardFrontendPath:
    description: 'path for typescript dashboard output'
    required: false
    default: '***SKIP***'
runs:
  using: "composite"
  steps:
    - uses: dawidd6/action-download-artifact@v2
      with:
        repo: "trinsic-id/protoc-gen-sdk"
        workflow: "build-plugin.yml"
        path: ${{ github.action_path }}
        branch: main
        # github_token: ${{ secrets.GITHUB_TOKEN }}
    - shell: bash
      run: |
        chmod +x "${{ github.action_path }}/go-plugin/protoc-gen-sdk-linux-x64"
    - id: protocgensdk
      name: Generate template code
      run: |
        ${{ github.action_path }}\action.ps1 -ProtoPath "${{ inputs.protoPath }}" -RenamePairs "${{ inputs.renamePairs }}" -PythonPath "${{ inputs.pythonPath }}" -DotnetPath "${{ inputs.dotnetPath }}" -DartPath "${{ inputs.dartPath }}" -GolangPath "${{ inputs.golangPath }}" -TypescriptPath "${{ inputs.typescriptPath }}" -JavaKotlinPath "${{ inputs.javaKotlinPath }}" -RubyPath "${{ inputs.rubyPath }}" -SwiftPath "${{ inputs.swiftPath }}" -DashboardBffPath "${{ inputs.dashboardBffPath }}" -DashboardFrontendPath "${{ inputs.dashboardFrontendPath }}"
      shell: pwsh
