name: 'Set Test Environment'
description: 'Set Test Environment Variables for Trinsic SDK - consolidate multiple possible inputs'
inputs:
  renamePairs:
    description: 'Mapping pairs for folder names'
    required: false
    default: 'trust-registry=trustregistry,universal-wallet=wallet,verifiable-credentials=credential,templates=template'
  pythonPath:
    description: 'path for python output'
    required: false
    default: '../sdk/python/trinsic'
  dotnetPath:
    description: 'path for .NET output'
    required: false
    default: '../sdk/dotnet/Trinsic'
  dartPath:
    description: 'path for dart output'
    required: false
    default: '../sdk/dart/lib/src'
  golangPath:
    description: 'path for golang output'
    required: false
    default: '../sdk/go/services'
  typescriptPath:
    description: 'path for typescript output'
    required: false
    default: '../sdk/web/src'
  javaKotlinPath:
    description: 'path for Java / Kotlin output'
    required: false
    default: '../sdk/java/src/main/java/trinsic/services'
  rubyPath:
    description: 'path for Ruby output'
    required: false
    default: '../sdk/ruby/lib/services'
  swiftPath:
    description: 'path for swift output'
    required: false
    default: '../sdk-swift/Sources/Trinsic'
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true
        cache-dependency-path: go.sum
    - id: pickvalidvalues
      name: Pick Valid Values
      run: action.ps1
      shell: pwsh