name: Build Plugin

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-golang-plugin:
    name: Release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ "linux", "darwin", "windows" ]
        goarch: [ "amd64"] # , "arm64" ] - TODO support ARM64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: go.sum
      - name: Build Golang
        run: |
          go version
          go mod vendor
          go build -o "protoc-gen-sdk-${{ matrix.goos }}-${{ matrix.goarch }}$( If ($IsWindows) {'.exe'} Else {''})"
        working-directory: ./
        shell: pwsh
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v3
        with:
          name: "go-plugin"
          path: ./protoc-gen-sdk-*