name: Build Plugin

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-golang-plugin:
    name: Build, Test
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: go.sum
      - name: Build Golang
        run: |
          go version
          go build
